name = "PatientLevelPrediction"
authors = ["JuliaHealth contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1933"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
OHDSICohortExpressions = "b1469e29-13af-4897-a4a9-3c363a260582"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ROCAnalysis = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"

[compat]
CSV = "0.10"
CategoricalArrays = "0.10.8"
DBInterface = "2.6.1"
DataFrames = "1.7"
Distributions = "0.25"
DuckDB = "1"
FunSQL = "0.14.3"
InvertedIndices = "1.3.1"
MLJBase = "1.7.0"
MLJDecisionTreeInterface = "0.4.2"
MLJLinearModels = "0.10.0"
MLJXGBoostInterface = "0.3.12"
OHDSICohortExpressions = "0.2"
PrettyTables = "2"
ROCAnalysis = "0.3.6"
julia = "1.10"
