[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
JuliaHealthZoo = "886f7c4e-9682-4e9f-af4c-faf876c81a31"

[compat]
Documenter = "1.17"
DocumenterVitepress = "0.3"
